### ISSUE TITLE
Error on compile

### ISSUE THREAD

**Issue by IlPicasso** [n0bodysec/NobodyFirewall#1]
Hello, I am getting this

.
root@ns533461:~/bot/firewall/NobodyFirewall# make
gcc -lpcap -lpthread nfwall.c -o nfwall
nfwall.c: In function ‘main’:
nfwall.c:96:10: warning: too many arguments for format [-Wformat-extra-args]
   printf("[!] Warning: Using default interface: \"%s\".\n\n", iface, argv[0]);
          ^
/tmp/ccRA0rDX.o: In function `main':
nfwall.c:(.text+0x4b): undefined reference to `pthread_create'
nfwall.c:(.text+0x1ca): undefined reference to `pcap_findalldevs'
nfwall.c:(.text+0x23c): undefined reference to `pcap_open_live'
nfwall.c:(.text+0x295): undefined reference to `pcap_setdirection'
nfwall.c:(.text+0x2b3): undefined reference to `pcap_loop'
collect2: error: ld returned 1 exit status
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 1
root@ns533461:~/bot/firewall/NobodyFirewall# nano nfwall.c

**Comment by n0bodysec** [comment]
Hi, which linux distribution do you use?
I recently uploaded a new fix, try out :)

Regards.
